#+TITLE: class:flags::flag
#+AUTHOR: Stephen P. Hurlsmith
#+DATE: <2025-07-02 Wed 18:42>

[[./index.org][Back to category]]

This class is a small structure which provides a flag object as
described in [[./abstract/commandline-parsing.org][Command line parsing]].  It is part of [[./namespace:flags.org][namespace:flags]].

It allows you to register an object with descriptions of whether it
accepts data or not, and what setting it pertains to.  It also manages
the responsibility of if the setting is valid.

* Description

Once you have a setting, and you would like to control the setting
through a command-line flag, you should register a flag object.  Since
flag objects rarely change, and so too do settings objects, you may
define it const and static.

If the setting you have pointed to has a valid values table, set the
accepts​_flag field to true.

This class itself does nothing but mark some information that the
parser can work with when trying to apply the behaviour of the flag
upon invocation.

* Specification

** bool flags::flag::accepts​_data

A field describing whether [[*settings::setting<int>* flags::flag::option][settings::setting<int>* flags::flag::option]] should
accept data; Whether or not the setting has a value table.

** settings::setting<int>* flags::flag::option

A field holding a pointer to a settings object the flag describes.

** bool flags::flag::shelled​_manage(std::string g​_data)

A function that indirectly calls [[./class:settings;setting.org::*void settings::setting::manage(string​_type g​_option)][void settings::setting::manage()]].  It
checks whether or not option is void before to avoid a program
failure, and instead returns flags::parser::FAILURE.
