#+TITLE: class:windows::window
#+AUTHOR: Stephen P. Hurlsmith
#+DATE: <2025-07-06 Sun 18:08>

[[./index.org][Back to category]]

The class windows::window is a class that registers a window in the
system's window manager.

* Description

Initialize this whenever you would like to use a window, and interface
with it to configure your window.

Good practice is to be frugal about calls inquiring the window's
attributes.  Store results of calls once and throw them out, as you
never know what the expense is for the library or the system.

* Specification

** windows::window::window(windows::window::resolution g_width, windows::window::resolution g_height, std::string g_name)

The constructor for a window.

g_width is given width of the window.
g_height is the given height of the window.
g_name is the given name of the window.

** windows::window::~window()

The destructor for a window.
Destroys the window in the system window manager and destroys the
window's resources.

** void windows::window::set_name(std::string g_name)

A mutator on the window name(title).

g_name supplies the window title.

** bool windows::window::valid()

A function returning a value indicating whether or not the window is
still registered and valid.

Returns windows::window::YES if yes and windows::window::NO if not.

** bool windows::window::should_close()

A function returning a value indicating whether or not the window
should close.  This is for use of handling an event/render loop.

Returns either windows::window::YES or windows::window::NO.

** windows::window::resolution windows::window::get_width()

A function returning the width of the framebuffer of the window in
pixels.

** windows::window::resolution windows::window::get_height()

A function returning the height of the framebuffer of the window in
pixels.

** std::string windows::window::get_name()

A function returning the title of the window as a string.

** static const bool windows::window::YES

A value indicating affirmation or success.

** static const bool windows::window::NO

A value indicating 'no' or failure.
** Misc.

windows::window::resolution is a typedef for int.
