#+TITLE: class:flags::parser
#+AUTHOR: Stephen P. Hurlsmith
#+DATE: <2025-07-03 Thu 10:37>

[[./index.org][Back to category]]

The parser class flags::parser, found in [[./namespace:flags.org][namespace:flags]] is the final
class in the command line parsing pipeline, which parses and applies
the invocations of the flags supplied in the invocation of the
program.

* Description

See [[./abstract/commandline-parsing.org][Command line parsing]].

* Specification

** flags::parser::parser(flags::flag​_table g​_flags)

This is the constructor.  You can supply flags::parser::flags to be
g​_flags, or set it yourself.

** bool flags::parser::parse(flags::sequence g​​_sequence)

This function parses a flags::sequence, expected to be generated in
format of long flags and data and marked accordingly.  Since that
isn't caller's concern, you should refer to [[./class:flags;sieve.org][class:flags::sieve]] for how
to generate a conforming sequence for this function.

This function will report errors if flags were not given the data they
expect. It will also report errors if given flags that do not have
records in its flag table.

It will return flags::parser::SUCCESS if it succeeded or
flags::parser::FAILURE if it failed.

** static const bool flags::parser::SUCCESS

A boolean return value for success.

** static const bool flags::parser::FAILURE

A boolean return value for failure;

** flag​_table flags::parser::flags

The flag table the parser will compare with.  Made public because
writing interfacing functions will only be an incomplete interface
with the flag, and it isn't main concern.
