#+TITLE: class:settings::setting
#+AUTHOR: Stephen P. Hurlsmith
#+DATE: <2025-07-02 Wed 12:28>

[[./index.org][Back to category]]

The settings::setting class - part of [[./namespace:settings.org][namespace:settings]] - is a class
template which provides the functionality needed to achieve the
specification of a settings object.  It is used by other classes to
denominate different behaviour they allow to be specified by the user.

This class uses [[./class:settings;handle.org][class:settings::handle]] to register handles on its
mutex, which provides functions with the ability to 'lock' a setting
from any other part of the program when it is utilizing the setting.
This is useful in concurrent use of a setting but is not mandatory to
use.

* Description

When you initialize an object of settings::setting, you are installing
a setting into whatever module you are writing.  This setting object
can control an atom of behaviour in a few ways, using the value that
it is given, in the context of the value table it was initialized
with, and it itself can hold information about whether or not it is in
use with its mutex.

The purpose of this class is to provide necessary functionality of a
variable which holds indicative data about how the module should
behave, with the convenience and advantage over a plain variable,
which must be checked extensively by all parties who make use of the
variable.

Of course, the settings object does not do this by itself; You, the
author of the module of functionality you are writing, must make use
of it correctly and reference it in the behaviour it pertains to
yourself to see its effect.  The settings object is a tool of
management over module behaviour.

** The indicative variable

The indicative variable is the variable holding the symbolic
information of the settings object.  It is what is used to determine
what behaviour is approriate.

The indicative variable is initialized with a default value, for when
the behaviour has not been specified.  This default value can be
changed in rare cases, but it takes effect only when the setting is
not in use.

The indicative variable can only have values from the value table
supplied to the settings object.

You should observe the value of the indicative variable to determine
what behaviour you must implement at the time the behaviour is
appropriate.  To make sense of it, you may compare it with the value
table.

You are discouraged from changing the default value of the indicative
variable with exception to a condition where you must change it
outside of initialization.

** The value table

The value table is the table of values that the indicative variable
may have.  It is a table that writes a value for the indicative
variable in comparison to a specific string specifying behaviour.

You should initialize a value table outside of the setting, and write
the values in terms of aliases or macros to make your code more
readable.  Then source it into the value table the settings object
references.

You are discouraged from changing the value table of your settings
object with exception to the condition that you must change it outside
of initialization.

** The settings object mutex

The mutex of the settings object is a mutex, which can be used in the
context of concurrent use of the same settings object.  You can
observe the value of the mutex from the setting.

If you are working with a settings object in concurrent use, you
should initialize a [[./class:settings;handle.org][class:settings::handle]] to your settings object,
hold the mutex with it, then drop the mutex when you are done
operating, and dispose of your handle accordingly.

Privileges of the mutex is that it protects changes over the setting's
default value, its value table, and the indicative value when it is
held.  You are guaranteed that when you hold a settings object's
mutex, you can treat the setting as if no other parties are acting
over it.

Again, the mutex is optional.  Some settings, which are not in
concurrent use, are not used with handles and explicitly held and
droppped.  Many settings disregard functionality of the mutex.

* Specification

** Initialization

settings::setting is a class template, and it has the following
template parameters:

#+BEGIN_SRC c++
  template <typename type, typename string_type, typename mutex_type, mutex_type m_default_value, mutex_type m_held_value>
#+END_SRC

'type' defines what type the variable holding the indicative data of
the setting should be.  For example, a setting with only 2 options
would only need 2 indicative values.  In that case, a bool type would
be fitting.

'string​_type' defines what kind of type should the string
specification of a setting should be.  It defaults to std::string
since that is what the c++ standard library presents for strings.

'mutex​_type' defines what kind of type the mutex should be.  For
support with all types, 2 values of type mutex​_type: m​_default​_value
and m​_held​_value must be supplied.  To make this choice simpler,
mutex​_type defaults to bool, m​_default​_value is false, and
m​_held​_value is true.

** settings::setting::setting(type g​_default​_value, table g​_values, void (*g​_responder)())

This is the constructor.

It initializes the default value of the indicative variable with
the given default value g​_default​_value.

It initializes the value table of the setting with g​_values.

It initializes its responder/callback function with the function
pointer g​_responder, of type void (*)().  This is an optional
parameter, so it can be specified NULL.

** void settings::setting::responder​_set(void (*g​_responder)())

This is a mutator function for the responder function.  It takes
g​_responder as a function pointer of the most basic type: void (*)().

** void settings::setting::default​_set(type g​_default​_value)

This is a mutator function for the default value of the indicative
value of the class.  It sets the default value in all cases, but this
change will only take effect if the setting's mutex is not held, to
enforce the protection of the setting mutex.

** void settings::setting::values​_set(table g​_values)

This is a mutator function for the value table of settings::setting.
It will reset the value of the indicative variable to default and
reset the value table to g​_values only under the condition that the
setting's mutex is not held.

** void settings::setting::manage(string​_type g​_option)

This function will search the value table for a value for the
indicative variable corresponding to the given string g​_option, and
set it to the indicative variable.

** mutex​_type settings::setting::held()

This is a selector function for observing the state of the setting's
mutex.  It returns the current value of the mutex at call time.

** type settings::setting::access()

This is a selector function for observing the state of the setting's
indicative variable.  It returns the value of the indicative variable.

** Misc.

The type 'table' is a typedef for
std::unordered​_map<string​_type, type>.

settings::setting defines [[./class:settings;handle.org][class:settings::handle]] as its friend.
