pkgdatadir=${datadir}/${PACKAGE}/archive/screenshots

dist_pkgdata_DATA=a_secret_cache-v0.2.12_14-alpha.png \
a_square.png \
a_triangle.png \
blue_win.png \
cliff-v0.2.11-alpha.png \
color_triangle_sawg.png \
cubs.png \
engineering_2050.png \
engineering_in_2072.png \
fucked_up_twins.png \
glfw_success.png \
glfw_triangle.png \
house-v0.2.12_14-alpha.png \
in_the_midstof_surgery.png \
life_is_pain_yay-v0.2.12_14-alpha.png \
Makefile.am \
scary-message.png \
shawa.png \
shredded.png \
the_pit-v0.2.11-alpha.png \
triplets_accurate.png \
triplets.png \
underside-v0.2.11-alpha.png \
uni_integrated.png \
uni_in_the_house-v0.2.12_14-alpha.png \
v0.0.0-alpha-corner.png \
v0.0.0-alpha-dissection.png \
v0.0.0-alpha-side.png \
v0.0.1-alpha_can_you_spot_the_uni.png \
v0.0.1-alpha_inside_the_uni.png \
v0.0.1-alpha_uni_corner.png \
v0.0.1-alpha_uni_rotate2.png \
v0.0.1-alpha_uni_rotate.png \
v0.0.1-alpha_uni_upsidedown.png \
v0.2.15-alpha-indev-shrine.png \
v0.2.15-alpha-indev-shrine-se.png \
wawa_cube.png \
wawa_far_away.png \
wawa_integrated.png \
wawa_integrated_randbow.png \
wawa_randbow.png \
wawatest_opengl.png \
wawa_tf.png \
wawa_tilted.png \
we_are_fucked.png \
wireframe-v0.2.11-alpha.png \
wonderful-v0.2.12_14-alpha.png 
