#+TITLE: Invoking Wawacraft:Evolved
#+DATE: <2025-08-11 Mon 17:00>
#+AUTHOR: Stephen P. Hurlsmith

Wawacraft:Evolved is a game, but in terse terms, Wawacraft:Evolved is
a program that you invoke on your computer, that runs arbitrary
instructions to run a simulation, which happens to be designed with
your entertainment in mind.

* Invocation from a GUI

To invoke Wawacraft:Evolved, you must have an environment to invoke
programs within.  If you would like to invoke the program from a GUI
file manager, go to the directory where Wawacraft:Evolved is stored,
and run the game.

You are also recommended to create a symlink to the program which
resides on your desktop, if you regularly invoke the game from a
desktop environment.

* Invocation from the TTY

To invoke from the TTY, you must first also find the directory (or
folder) that the game is stored in, and run it from there.

Usually, the game is stored in the following directory:

 + In bin/output/ relative to the project directory

Here, the project directory refers to the directory created by the
command you used to clone the game from a repository, or where you
installed the development codebase.  Usually, you would clone the game
using a git command:

git clone protocol://gamerepository/wawacraft-evolved

And whatever the repository's address is.

** PATH

If you are frequently developing the game, and would also like to run
it without running it in the directory, you should configure your
$PATH environment temporarily to include the bin/output/ directory the
game is found within.

In a BASH environment, you may do it like this:
#+BEGIN_SRC bash
  PATH=$PATH:~/projects/wawacraft-evolved/bin/output/
#+END_SRC

Since this is only present in your session, it will cease to be valid
once you exit the terminal session.

This is very useful for developers of the game who would like to not
waste time listing out redundant information about the program's path
each time to run it.

You could also make running the game even easier by providing a
shorter program name.

** Creating symlinks to the program.

In the directory the game is stored, you may create a symlink to the
file, in combination to the [[*PATH][PATH]] solution proposed earlier. You can
run the following in the directory of the program:

#+BEGIN_SRC bash
  ln --symbolic wawacraft-evolved wacre
#+END_SRC

This will create a symlink wacre in your directory, which you can call
instead of the actual program for a shorter filename.

** Invocation options

To see invocation options for the program at a glance, please run
'wawacraft-evolved -​-help' for all the options you may use.
