#+TITLE: Command line parsing
#+AUTHOR: Stephen P. Hurlsmith
#+DATE: <2025-06-30 Mon 13:33>

[[./index.org][Back to category]]

Command-line parsing, flags parsing, option parsing, command line
options parsing - whatever the hell it's called - is managed in the
source code using a pipeline of different classes.

Firstly, each module in the program registers settings objects, with
optional tables for values of the setting depending on the input
given, and a mandatory default value if untouched, as well as an
optional pointer to a response callback called whenever the setting
object's value is changed.

Then, a flag object is registered to describe the behaviour of a flag
and its corresponding setting.  This entails whether or not it needs
to accept data and what setting it controls.

Then, the invocations of the flag are added to a flag table, a flag
synonym table, and a pseudo-flag table.

* Describing the pipeline
** Settings objects

As the first stage of the pipeline, we start with a module or a class.
The class may exhibit behaviour which would be convenient to observe
in different ways.

A current example is the [[./logging.org][log object]], used in the logging system to
standardize program output.  Log objects output messages, records, and
errors.  Whilst all of these are useful for developers, whilst testing
and debugging a feature, the user cares not for what a function x in
scope y has achieved or even if it failed or not in some cases.

So the author of the log class registers some settings like in Figure
1.1-1:

Figure 1.1-1:

#+NAME: F.1.1-1
#+BEGIN_SRC c++ :eval never
  // NOTE: settings::setting<type> is defined
  // in include/program/settings.hpp
  
  //declaration
  public static settings::setting<type> FEATURE_SETTING;
  //definition
  static settings::setting<type> class::FEATURE_SETTING(DEFAULT_VALUE, FEATURE_TABLE, &response_function);
#+END_SRC

in their class, with their respective value tables, default values,
and response callbacks - functions that take the responsibility of
whatever behaviour is specified upon the change of a setting's value.
They could also not list a response function if the setting behaviour
checks the setting's value regularly.

The value table is an std::unordered​_map<string​_type, type>
which lists a corresponding value for the setting for each mode
specified. The mode string describes what data input will have to be
given to the option that controls the setting to activate the mode in
the class, so a setting that's controlled by a flag --flag and has
modes 'default' for default and 'expert' for expert behaviour would
need to be invoked as '--flag default' for default behaviour, and
'--flag expert' for expert behaviour.

:NOTE:
Note: since the table rarely changes at runtime, you may specify it
as const, and you may also specify the type aliases for each value
type VALUE​_ALIAS; as const as well.  It's actually good practice!
:END:

** Flag objects

This part of the pipeline is pretty easy.  You must initialize a flag
object like in Figure 1.2-1:

Figure 1.2-1:

#+NAME: F.1.2-1
#+BEGIN_EXAMPLE
  // NOTE: struct flags::flag is defined in include/program/flags.hpp

  // declaration
  extern flags::flag feature_flag;
  // definition
  // note that it's strange to see a bool aliased in the codebase
  // it is only done here to show you what each field means.

  const bool ACCEPTS_DATA=true;
  const bool ACCEPTS_DATA_NOT=false;

  flags::flag feature_flag={ACCEPTS_DATA, &namespace::class::FEATURE_SETTING};
#+END_EXAMPLE

flags::flag has a function, flags::flag::shelled​_manage(std::string)
which is called by flags::parser::call​_flag(flags::flag&, std::string)
when the parser determines it is an appropriate time to apply the
behaviour invoked by the flag.

** Registering invocation in invocation tables

For the sake of convenience, I'll refer to the flag table, the synonym
table, and the pseudo-flag table as a group: the /invocation tables/.

/Invocation tables/ describe what invocations should be accepted, and
what flags they are tied to.  Each table describes a map between one
invocation type and another, or an invocation to a flag.

It might occur to you that the registering of all these tables, their
listing, and their maintaining is a long and painful process akin to
documentation.  This is why, in the source code, we only manage such a
thing in include/options.hpp and src/options.cpp.  Despite the
object-oriented structure, you only need to parse the command-line
options once, so these tables are rarely found anywhere else.

*** Flag tables

This is a direct invocation table - in source code registered as an
std::unordered​_map<std::string, flag> - which maps 'long-flag' option
invocation to flag objects.  The parser class flags::parser expects
its input to be solely constructed of -​-long-flags and data strings in
order.  flags::sieve filters the real invocation - like a sieve - to
it's pure format that is accepted by the parser.

*** Synonym tables

This is an indirect invocation table - in source code registered as an
std::unordered​_map<char, std::string>.

Synonym tables describe the short-flag synonyms of a long flag.  Since
short-flags can be stacked like -abcdefg, each short-flag letter is
listed and mapped to a long flag.

Sieves use this and [[*Pseudo-flag tables][Pseudo-flag tables]] to sieve invocation into a
homogenous format.

*** Pseudo-flag tables

Since all 'real' flags invoked will always control only one piece of
behaviour, and usually a common pattern of behaviour oversees lots of
other behaviours, pseudo-flags exist.

Pseudo-flags are not real flags, in that they are not mapped to
registered flag objects nor do they have settings.  They instead are
invocations that map to more terse combinations of invocations of
'real' flags.

In source code, this is handled in an ugly way; the converted
invocation is embedded as an std::vector<std::string> instead of a
long string, so "-​-long-flag -gibblebibbledoo data a four 3" would be
listed as {"-​-long-flag", "-gibblebibbledoo", "data", "a", "four",
"3"}.  I'm already thinking about creating a function that converts
regular strings into such a format for my own convenience.

* Use

You should refer to the documentation of the respective classes on how
to register settings, flags, etc.  This section will describe some of
the [[*Styles of use][styles of use]] that are prominent in the codebase.

** Styles of use

*** Flags specifying behaviour

This is the standard style of use for registering flags and settings.
Usually, the behaviour exists outside of the control of the setting,
but can be altered through it.

*** Flags invoking behaviour

Different from the previous style, flags *invoking behaviour* usually
do not accept data, and their module is started from the response
function.  This is so that whenever the flag is invoked, code from the
module runs.  Working examples of this are in src/blurbs.cpp and
include/blurbs.hpp where the blurbs for help and version display are.
All the behaviour is written in a callback function, or at least
started from it.

You could either make these kinds of modules not accept data, like in
the case for the version blurb and the help blurb, or have them accept
data.  This would make a flag specifying behaviour wherein the
specification is whether the behaviour runs or not, and to mimic the
effect of a flag being invoked without data, you could hook a
pseudo-flag to be invoked in its place.
